### ISSUE TITLE
Does not page jump to top 1st post

### ISSUE THREAD

**Issue by Nirjonadda** [kalynrobinson/xf2_ajax_paging#3]
@kalynrobinson , One bug found, changing tread pages from footer then does not page jump to top 1st post.

**Comment by kalynrobinson** [comment]
Thank you for the bug report. I mentioned this as well on your other issue, but I've just released a fix for this. Sorry for the inconvenience—let me know if that fixes your issue.

[1.0.0 Beta 6](https://github.com/kalynrobinson/xf2_ajax_paging/releases/tag/v1.0.0-beta.6)

**Comment by Nirjonadda** [comment]
@kalynrobinson not fixed, its not jump to page 1st post from below page nav.

See here: https://giant.gfycat.com/AptSnivelingArcticwolf.webm

**Comment by Nirjonadda** [comment]
@kalynrobinson Please Do you have any update ?
